# Generated by Django 5.0.1 on 2024-02-15 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id_categorias', models.AutoField(primary_key=True, serialize=False)),
                ('categorias', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cidade', models.SlugField(max_length=254, unique=True, verbose_name='cidade')),
                ('descricao', models.TextField(verbose_name='descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('nome_local', models.CharField(max_length=254, verbose_name='Nome do Local')),
                ('descricao', models.CharField(max_length=254, verbose_name='Descrição')),
                ('bairro', models.CharField(max_length=254, verbose_name='Bairro')),
                ('rua', models.CharField(max_length=254, verbose_name='Rua')),
                ('telefone', models.CharField(blank=True, max_length=14, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local', to='smarttravel.cidade')),
                ('tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locais', to='smarttravel.categorias')),
            ],
        ),
    ]
