# Generated by Django 5.0.1 on 2024-02-16 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarttravel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cidade',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='imagens/'),
        ),
        migrations.AddField(
            model_name='local',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='local', verbose_name='Imagem'),
        ),
    ]
