# Generated by Django 5.0.1 on 2024-02-25 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarttravel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cidade',
            name='nome_cidade',
            field=models.CharField(max_length=254, unique=True, verbose_name='cidade'),
        ),
    ]
