# Generated by Django 5.0.1 on 2024-02-25 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarttravel', '0002_alter_cidade_nome_cidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='locais/', verbose_name='Imagem'),
        ),
    ]
