# Generated by Django 5.0.1 on 2024-02-27 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarttravel', '0004_local_latitude_local_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorias',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='categorias/', verbose_name='Imagem'),
        ),
    ]
