# Generated by Django 5.0.1 on 2024-02-20 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smarttravel', '0004_remove_roteiro_data_viagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roteiro',
            name='quantidade_pessoas',
        ),
    ]
