# Generated by Django 5.0.1 on 2024-02-27 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smarttravel', '0005_categorias_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='local',
            name='email',
        ),
    ]
