# Generated by Django 4.2.8 on 2024-02-21 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smarttravel', '0005_remove_roteiro_quantidade_pessoas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Roteiro',
        ),
    ]
