# Generated by Django 5.0.1 on 2024-02-21 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarttravel', '0006_delete_roteiro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
